//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rolex {
    using System;
    using System.IO;
    using System.Collections.Generic;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Rolex", "0.8.0.0")]
    internal struct Token {
        public int Line;
        public int Column;
        public long AbsoluteIndex;
        public long Position;
        public int SymbolId;
        public string Value;
    }
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Rolex", "0.8.0.0")]
    internal class TableTokenizer : object, IEnumerable<Token> {
        public const int ErrorSymbol = -1;
        private int[] _dfaTable;
        private int[][] _blockEnds;
        private int[] _nodeFlags;
        private IEnumerable<char> _input;
        public IEnumerator<Token> GetEnumerator() {
            return new TableTokenizerEnumerator(this._dfaTable, this._blockEnds, this._nodeFlags, this._input.GetEnumerator());
        }
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
            return this.GetEnumerator();
        }
        public TableTokenizer(int[] dfaTable, int[][] blockEnds, int[] nodeFlags, IEnumerable<char> input) {
            if ((null == dfaTable)) {
                throw new ArgumentNullException("dfaTable");
            }
            if ((null == blockEnds)) {
                throw new ArgumentNullException("blockEnds");
            }
            if ((null == nodeFlags)) {
                throw new ArgumentNullException("nodeFlags");
            }
            if ((null == input)) {
                throw new ArgumentNullException("input");
            }
            this._dfaTable = dfaTable;
            this._blockEnds = blockEnds;
            this._nodeFlags = nodeFlags;
            this._input = input;
        }
    }
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Rolex", "0.8.0.0")]
    internal class TableTokenizerEnumerator : object, IEnumerator<Token> {
        private int _state;
        private Token _token;
        private int _ch;
        private int[] _dfa;
        private int[][] _blockEnds;
        private int[] _nodeFlags;
        private long _position;
        private long _absIndex;
        private int _line;
        private int _column;
        private StringBuilder _capture = new StringBuilder();
        private IEnumerator<char> _inner;
        public TableTokenizerEnumerator(int[] dfa, int[][] blockEnds, int[] nodeFlags, IEnumerator<char> inner) {
            this._position = 0;
            this._line = 1;
            this._column = 1;
            this._absIndex = 0;
            this._dfa = dfa;
            this._blockEnds = blockEnds;
            this._nodeFlags = nodeFlags;
            this._inner = inner;
            this._ch = -2;
            this._token.SymbolId = -2;
            this._state = -1;
        }
        public Token Current {
            get {
                if ((this._state == -3)) {
                    throw new ObjectDisposedException("The enumerator was disposed");
                }
                else {
                    if (((this._state == -2) 
                                || (this._state == -1))) {
                        throw new InvalidOperationException("The enumerator is not positioned on an element");
                    }
                }
                return this._token;
            }
        }
        object System.Collections.IEnumerator.Current {
            get {
                return this.Current;
            }
        }
        void System.IDisposable.Dispose() {
            this.Dispose();
        }
        public void Dispose() {
            if ((this._state == -3)) {
                return;
            }
            this._inner.Dispose();
            this._state = -3;
        }
        private bool _FetchNextInput() {
            if ((false == this._inner.MoveNext())) {
                this._ch = -1;
                return false;
            }
            char ch1 = this._inner.Current;
            if (char.IsHighSurrogate(ch1)) {
                if ((false == this._inner.MoveNext())) {
                    throw new IOException("The stream is not valid Unicode");
                }
                char ch2 = this._inner.Current;
                if ((false == char.IsLowSurrogate(ch2))) {
                    throw new IOException("The stream is not valid Unicode");
                }
                this._absIndex = (this._absIndex + 1);
                this._column = (this._column + 1);
                this._ch = char.ConvertToUtf32(ch1, ch2);
            }
            else {
                if ((ch1 == '\r')) {
                    this._column = 1;
                }
                else {
                    if ((ch1 == '\n')) {
                        this._line = (this._line + 1);
                        this._column = 1;
                    }
                    else {
                        if ((ch1 == '\t')) {
                            this._column = (((this._column / 4) 
                                        + 1) 
                                        * 4);
                        }
                        else {
                            this._column = (this._column + 1);
                        }
                    }
                }
                this._ch = System.Convert.ToInt32(ch1);
            }
            this._position = (this._position + 1);
            this._absIndex = (this._absIndex + 1);
            return true;
        }
        bool System.Collections.IEnumerator.MoveNext() {
            return this.MoveNext();
        }
        public bool MoveNext() {
            if ((this._state == -3)) {
                throw new ObjectDisposedException("The enumerator was disposed");
            }
            else {
                if ((this._state == -1)) {
                    this._state = 0;
                }
            }
            if ((this._state == 0)) {
                for (
                ; true; 
                ) {
                    if ((this._ch == -1)) {
                        this._state = -2;
                        return false;
                    }
                    this._Lex();
                    if ((this._token.SymbolId > -1)) {
                        if ((0 
                                    == (this._nodeFlags[this._token.SymbolId] & 1))) {
                            return true;
                        }
                    }
                    else {
                        return true;
                    }
                }
            }
            return false;
        }
        void System.Collections.IEnumerator.Reset() {
            this.Reset();
        }
        public void Reset() {
            if ((this._state == -3)) {
                throw new ObjectDisposedException("The enumerator was disposed");
            }
            this._state = -1;
            this._ch = -2;
            this._position = 0;
            this._absIndex = 0;
            this._line = 1;
            this._column = 1;
            this._token.SymbolId = -2;
        }
        public long AbsoluteIndex {
            get {
                if ((this._state == -3)) {
                    throw new ObjectDisposedException("The enumerator was disposed");
                }
                return this._absIndex;
            }
        }
        public long Position {
            get {
                if ((this._state == -3)) {
                    throw new ObjectDisposedException("The enumerator was disposed");
                }
                return this._position;
            }
        }
        public int Line {
            get {
                if ((this._state == -3)) {
                    throw new ObjectDisposedException("The enumerator was disposed");
                }
                return this._line;
            }
        }
        public int Column {
            get {
                return this._column;
            }
        }
        bool _Lex() {
            int tlen;
            int tto;
            int prlen;
            int pmin;
            int pmax;
            int i;
            int j;
            int state = 0;
            int acc;
            long cursor_pos = this._position;
            int line = this._line;
            int column = this._column;
            long absi = this._absIndex;
            if ((this._ch == -2)) {
                this._FetchNextInput();
                if ((this._ch == -1)) {
                    this._state = -2;
                    return false;
                }
            }
            else {
                if ((this._ch == -1)) {
                    this._state = -2;
                    return false;
                }
            }
            this._token.Position = cursor_pos;
        start_dfa:

            acc = this._dfa[state];
            state = (state + 1);
            tlen = this._dfa[state];
            state = (state + 1);
            for (i = 0; (i < tlen); i = (i + 1)) {
                tto = this._dfa[state];
                state = (state + 1);
                prlen = this._dfa[state];
                state = (state + 1);
                for (j = 0; (j < prlen); j = (j + 1)) {
                    pmin = this._dfa[state];
                    state = (state + 1);
                    pmax = this._dfa[state];
                    state = (state + 1);
                    if ((this._ch < pmin)) {
                        state = (state 
                                    + ((prlen 
                                    - (j + 1)) 
                                    * 2));
                        j = prlen;
                    }
                    else {
                        if ((this._ch <= pmax)) {
                            this._capture.Append(char.ConvertFromUtf32(this._ch));
                            this._FetchNextInput();
                            state = tto;
                            goto start_dfa;
                        }
                    }
                }
            }
            if ((false 
                        == (acc == -1))) {
                int sym = acc;
                int[] be = this._blockEnds[acc];
                if ((be != null)) {
                    state = 0;
                start_be_dfa:

                    acc = be[state];
                    state = (state + 1);
                    tlen = be[state];
                    state = (state + 1);
                    for (i = 0; (i < tlen); i = (i + 1)) {
                        tto = be[state];
                        state = (state + 1);
                        prlen = be[state];
                        state = (state + 1);
                        for (j = 0; (j < prlen); j = (j + 1)) {
                            pmin = be[state];
                            state = (state + 1);
                            pmax = be[state];
                            state = (state + 1);
                            if ((this._ch < pmin)) {
                                state = (state 
                                            + ((prlen 
                                            - (j + 1)) 
                                            * 2));
                                j = prlen;
                            }
                            else {
                                if ((this._ch <= pmax)) {
                                    this._capture.Append(char.ConvertFromUtf32(this._ch));
                                    this._FetchNextInput();
                                    state = tto;
                                    goto start_be_dfa;
                                }
                            }
                        }
                    }
                    if ((false 
                                == (acc == -1))) {
                        this._token.SymbolId = sym;
                        this._token.Value = this._capture.ToString();
                        this._token.AbsoluteIndex = absi;
                        this._token.Position = cursor_pos;
                        this._token.Line = line;
                        this._token.Column = column;
                        this._capture.Clear();
                        return true;
                    }
                    if ((this._ch == -1)) {
                        this._token.SymbolId = -1;
                        this._token.Value = this._capture.ToString();
                        this._token.AbsoluteIndex = absi;
                        this._token.Position = cursor_pos;
                        this._token.Line = line;
                        this._token.Column = column;
                        this._capture.Clear();
                        return false;
                    }
                    this._capture.Append(char.ConvertFromUtf32(this._ch));
                    this._FetchNextInput();
                    state = 0;
                    goto start_be_dfa;
                }
                this._token.SymbolId = acc;
                this._token.Value = this._capture.ToString();
                this._token.AbsoluteIndex = absi;
                this._token.Position = cursor_pos;
                this._token.Line = line;
                this._token.Column = column;
                this._capture.Clear();
                return true;
            }
            bool fetch = (this._capture.Length == 0);
            if (fetch) {
                this._capture.Append(char.ConvertFromUtf32(this._ch));
            }
            this._token.SymbolId = -1;
            this._token.Value = this._capture.ToString();
            this._token.AbsoluteIndex = absi;
            this._token.Position = cursor_pos;
            this._token.Line = line;
            this._token.Column = column;
            this._capture.Clear();
            if (fetch) {
                this._FetchNextInput();
            }
            return false;
        }
    }
    internal class ExampleTokenizer : TableTokenizer {
        internal static int[] DfaTable = new int[] {
                -1,
                15,
                64,
                2,
                9,
                13,
                32,
                32,
                72,
                1,
                34,
                34,
                98,
                1,
                44,
                44,
                100,
                1,
                45,
                45,
                184,
                1,
                47,
                47,
                110,
                1,
                48,
                48,
                168,
                1,
                49,
                57,
                192,
                1,
                58,
                58,
                194,
                1,
                91,
                91,
                196,
                1,
                93,
                93,
                198,
                1,
                102,
                102,
                224,
                1,
                110,
                110,
                244,
                1,
                116,
                116,
                264,
                1,
                123,
                123,
                266,
                1,
                125,
                125,
                19,
                1,
                64,
                2,
                9,
                13,
                32,
                32,
                -1,
                3,
                72,
                3,
                0,
                33,
                35,
                91,
                93,
                1114111,
                90,
                1,
                34,
                34,
                92,
                1,
                92,
                92,
                11,
                0,
                -1,
                1,
                72,
                1,
                0,
                1114111,
                10,
                0,
                -1,
                2,
                110,
                1,
                48,
                48,
                168,
                1,
                49,
                57,
                15,
                3,
                126,
                1,
                46,
                46,
                132,
                1,
                48,
                57,
                144,
                2,
                69,
                69,
                101,
                101,
                -1,
                1,
                132,
                1,
                48,
                57,
                15,
                2,
                132,
                1,
                48,
                57,
                144,
                2,
                69,
                69,
                101,
                101,
                -1,
                2,
                156,
                2,
                43,
                43,
                45,
                45,
                162,
                1,
                48,
                57,
                -1,
                1,
                162,
                1,
                48,
                57,
                15,
                1,
                162,
                1,
                48,
                57,
                15,
                3,
                126,
                1,
                46,
                46,
                168,
                1,
                48,
                57,
                144,
                2,
                69,
                69,
                101,
                101,
                -1,
                1,
                190,
                1,
                42,
                42,
                7,
                0,
                12,
                0,
                13,
                0,
                14,
                0,
                -1,
                1,
                204,
                1,
                97,
                97,
                -1,
                1,
                210,
                1,
                108,
                108,
                -1,
                1,
                216,
                1,
                115,
                115,
                -1,
                1,
                222,
                1,
                101,
                101,
                18,
                0,
                -1,
                1,
                230,
                1,
                117,
                117,
                -1,
                1,
                236,
                1,
                108,
                108,
                -1,
                1,
                242,
                1,
                108,
                108,
                16,
                0,
                -1,
                1,
                250,
                1,
                114,
                114,
                -1,
                1,
                256,
                1,
                117,
                117,
                -1,
                1,
                262,
                1,
                101,
                101,
                17,
                0,
                8,
                0,
                9,
                0};
        internal static int[] NodeFlags = new int[] {
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1};
        internal static int[][] BlockEnds = new int[][] {
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                new int[] {
                        -1,
                        1,
                        6,
                        1,
                        42,
                        42,
                        -1,
                        1,
                        12,
                        1,
                        47,
                        47,
                        0,
                        0},
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null};
        public ExampleTokenizer(IEnumerable<char> input) : 
                base(ExampleTokenizer.DfaTable, ExampleTokenizer.BlockEnds, ExampleTokenizer.NodeFlags, input) {
        }
        public const int comment_block = 7;
        public const int lbrace = 8;
        public const int rbrace = 9;
        public const int comma = 10;
        public const int @string = 11;
        public const int colon = 12;
        public const int lbracket = 13;
        public const int rbracket = 14;
        public const int number = 15;
        public const int @null = 16;
        public const int @true = 17;
        public const int @false = 18;
        public const int whitespace = 19;
    }
}
